baseURL = 'https://Aru556880.github.io/'
languageCode = 'en-us'
title = 'Aru's site'

theme = "manis"

[menu]
  [[menu.main]]
    identifier = "post"
    url = "/post/"
    # title will be shown when you hover on this menu link
    title = "Aru's site"
    weight = 1